# CodeRabbit Configuration for PMOVES.AI
# Settings for automated code reviews

reviews:
  # Enable reviews on the default hardened branch
  review_status: true

  # Branches to review
  branches:
    - "PMOVES.AI-Edition-Hardened"
    - "PMOVES.AI-Edition-Hardened-v3-clean"
    - "pr/hirag-legacy-decoders-v3-clean"
    - "pr/*"          # PR branches
    - "feat/hardened-*"
    - "fix/hardened-*"
    - "feat/*"          # Feature branches
    - "fix/*"           # Fix branches
    - "gpu-*"           # GPU orchestrator fixes
    - "remove-*"        # Submodule removals
    - "revert-*"        # Revert PRs

  # Disable reviews on these branches
  excluded_branches:
    - "main"
    - "origin/main"

# Language setting (locale for reviews)
language: "en-US"

# Note: Documentation coverage and review depth settings are configured
# via GitHub Actions and CI/CD pipelines. CodeRabbit focuses on automated
# code quality checks and security scanning.
