# PMOVES.AI Agent Orchestration Config
# Implements the "BotZ" multi-agent swarm architecture
# Reference: pmoves/docs/AGENTS/ALIGNED_IMPLEMENTATION_ROADMAP.md
#
# Thread Types:
#   Base (B): Single prompt-response
#   Parallel (P): Multiple agents simultaneously
#   Chained (C): Sequential dependencies
#   Fusion (F): Multi-model consensus
#   Big (L): Large-scale autonomous planning
#   Long (Z): Long-running background tasks

procs:
  # ============================================================================
  # 1. THE GATEWAY (The Manager)
  # ============================================================================
  # Listens for user intent and dispatches tasks to subagents.
  # Integrates with mprocs remote control server for dynamic thread spawning.
  gateway:
    cmd: ["python", "-m", "gateway.gateway"]
    cwd: "/app/python/gateway"
    autostart: true
    env:
      MPLCROCS_SERVER: "127.0.0.1:4050"
      AGENT_ROLE: "gateway"
      # TensorZero for LLM routing in docked mode
      TENSORZERO_BASE_URL: "${TENSORZERO_BASE_URL:-http://tensorzero-gateway:3030}"
      # NATS for cross-service coordination
      NATS_URL: "${NATS_URL:-nats://nats:4222}"
      # HiRAG for knowledge retrieval
      HIRAG_URL: "${HIRAG_URL:-http://hirag:8086}"

  # ============================================================================
  # 2. THE ARCHITECT (The Brain - Opus 4.5)
  # ============================================================================
  # Used for high-level planning and "King Mode" reasoning.
  # Reads memory/architecture.md first, outputs PLANS not code.
  # In docked mode: Uses TensorZero orchestrator function.
  architect:
    shell: |
      echo "Architect Agent (Opus 4.5) - Planning Mode"
      echo "Reading: pmoves/docs/architecture/"
      echo "Integration: pmoves/docs/AGENTS/"
      echo "Constraints: security/patterns.yaml"
      if [ "${PMOVES_DOCKED_MODE}" = "true" ]; then
        echo "Model: TensorZero/orchestrator (docked)"
      else
        echo "Model: claude-opus-4-5 (standalone)"
      fi
      echo "Ready for planning tasks..."
    cwd: "."
    stop: "SIGTERM"
    env:
      AGENT_ROLE: "architect"
      MODEL: "opus-4-5"
      SKILL_PATH: "skills/orchestrator"
      # Docked: TensorZero function routing
      TENSORZERO_FUNCTION: "orchestrator"

  # ============================================================================
  # 3. THE BUILDER (The Hands - Sonnet 3.5)
  # ============================================================================
  # Executes the plans generated by the Architect.
  # Runs in sandboxed environment when available.
  builder:
    shell: |
      echo "Builder Agent (Sonnet 3.5) - Execution Mode"
      echo "Sandbox: ${E2B_API_KEY:+E2B}${E2B_API_KEY:-Docker}"
      if [ "${PMOVES_DOCKED_MODE}" = "true" ]; then
        echo "Model: TensorZero/utility (docked)"
      else
        echo "Model: claude-sonnet-4-5 (standalone)"
      fi
      echo "Ready for build tasks..."
    cwd: "."
    env:
      AGENT_ROLE: "builder"
      MODEL: "sonnet-4-5"
      SKILL_PATH: "skills/code-builder"
      SANDBOX: "true"
      # E2B sandbox (optional)
      E2B_API_KEY: "${E2B_API_KEY:-}"
      # Docked: TensorZero function
      TENSORZERO_FUNCTION: "utility"

  # ============================================================================
  # 4. THE AUDITOR (The Conscience - Haiku)
  # ============================================================================
  # Runs probabilistic safety checks on code changes.
  # Uses security hooks (patterns.yaml + hooks/*.py).
  auditor:
    shell: |
      echo "Auditor Agent (Haiku) - Security Review Mode"
      echo "Patterns: security/patterns.yaml"
      echo "Hooks: security/hooks/deterministic.py, security/hooks/probabilistic.py"
      echo "Audit log: memory/audit/"
      echo "Ready for security assessments..."
    cwd: "."
    env:
      AGENT_ROLE: "auditor"
      MODEL: "haiku"
      SKILL_PATH: "skills/security-auditor"
      # Security hooks config
      PATTERNS_PATH: "security/patterns.yaml"
      AUDIT_LOG_PATH: "memory/audit/agent_actions.log"

  # ============================================================================
  # 5. RESEARCHER (The Eyes - Sonnet 3.5)
  # ============================================================================
  # Information gathering and analysis.
  # In docked mode: Can query HiRAG for knowledge retrieval.
  researcher:
    shell: |
      echo "Researcher Agent - Information Gathering Mode"
      echo "Output: memory/research/"
      if [ "${PMOVES_DOCKED_MODE}" = "true" ]; then
        echo "HiRAG: ${HIRAG_URL:-http://hirag:8086} (knowledge retrieval)"
        echo "SupaSerch: ${SUPASERCH_URL:-http://supaserch:8099} (deep research)"
      else
        echo "Using: Local search and memory"
      fi
      echo "Ready for research tasks..."
    cwd: "."
    autostart: false
    env:
      AGENT_ROLE: "researcher"
      MODEL: "sonnet-4-5"
      # Docked: HiRAG knowledge retrieval
      HIRAG_URL: "${HIRAG_URL:-}"
      SUPASERCH_URL: "${SUPASERCH_URL:-}"

  # ============================================================================
  # 6. NATS MONITOR (Docked Mode Only)
  # ============================================================================
  # Subscribes to PMOVES.AI event bus for cross-service coordination.
  nats-monitor:
    shell: |
      if [ "${PMOVES_DOCKED_MODE}" = "true" ]; then
        echo "NATS Monitor - Subscribing to agent-zero.* subjects..."
        echo "NATS URL: ${NATS_URL:-nats://nats:4222}"
        echo "Subjects:"
        echo "  - agent-zero.agent.thread.started.v1"
        echo "  - agent-zero.agent.thread.completed.v1"
        echo "  - agent-zero.tool.executed.v1"
        echo "Awaiting messages..."
      else
        echo "NATS Monitor disabled (standalone mode)"
        echo "Set PMOVES_DOCKED_MODE=true to enable"
      fi
    cwd: "."
    autostart: false
    env:
      NATS_URL: "${NATS_URL:-nats://nats:4222}"

  # ============================================================================
  # 7. LOG VIEWER
  # ============================================================================
  # Tail the audit log for monitoring.
  logs:
    shell: "tail -f memory/audit/agent_actions.log 2>/dev/null || echo 'Awaiting audit logs...'"
    cwd: "."
    autostart: false

  # ============================================================================
  # 8. HEALTH CHECK
  # ============================================================================
  # Validates service dependencies based on mode.
  health:
    shell: |
      echo "=== Agent Zero Health Check ==="
      if [ "${PMOVES_DOCKED_MODE}" = "true" ]; then
        echo "Checking docked dependencies..."
        curl -sf ${TENSORZERO_BASE_URL:-http://tensorzero-gateway:3030}/healthz && echo "TensorZero: OK" || echo "TensorZero: FAIL"
        curl -sf ${HIRAG_URL:-http://hirag:8086}/healthz && echo "HiRAG: OK" || echo "HiRAG: FAIL (optional)"
        curl -sf ${NATS_URL:-nats://nats:4222} -o /dev/null && echo "NATS: OK" || echo "NATS: FAIL"
      else
        echo "Mode: Standalone - checking local services..."
        echo "Claude API: ${ANTHROPIC_API_KEY:+configured}"
      fi
      echo "==============================="
    cwd: "."
    autostart: false
    autorestart: false

# ============================================================================
# Remote Control Server
# ============================================================================
# Allows the 'Gateway' to programmatically spawn new agent threads.
# Enables dynamic Parallel Thread (P) patterns for concurrent execution.
server: "127.0.0.1:4050"

# ============================================================================
# Keymaps for "In-Loop" Control
# ============================================================================
keymap:
  global:
    "C-g": { c: "focus-proc", name: "gateway" }      # Jump to Gateway
    "C-a": { c: "focus-proc", name: "architect" }    # Jump to Architect
    "C-b": { c: "focus-proc", name: "builder" }      # Jump to Builder
    "C-s": { c: "focus-proc", name: "auditor" }      # Jump to Auditor (S for Security)
    "C-r": { c: "focus-proc", name: "researcher" }   # Jump to Researcher
    "C-n": { c: "focus-proc", name: "nats-monitor" } # Jump to NATS Monitor
    "C-l": { c: "focus-proc", name: "logs" }         # Jump to Logs
    "C-h": { c: "focus-proc", name: "health" }       # Jump to Health
    "C-x": { c: "term-proc" }                        # Kill selected agent
    "C-k": { c: "send-keys", keys: "C-c" }           # Send interrupt to agent

# ============================================================================
# Layout configuration
# ============================================================================
layout:
  type: "columns"
  procs:
    - gateway
    - architect
    - builder
    - auditor
